### PR TITLE
change default baseurl to localhost

### PR DESCRIPTION
**Pull request by liuzhongshu**

### CODE REVIEW

**Comment by fzaninotto** [comment]
Why? This is the code running the demo at ng-admin.marmelab.com. We need this.

**Comment by liuzhongshu** [comment]
For someone who want use this code to see a demo of ng-admin, set baseurl to localhost will let the code just works.

**Comment by jpetitcolas** [comment]
If you just want to launch the demo, use `make run`, and then access it via [http://localhost:8000](http://localhost:8000).

**Comment by liuzhongshu** [comment]
I can launch the demo and access it via http://localhost:3000 (not 8000), but if i not change the baseApiUrl, when I do some opertaion, the request will be send to ng-admin.marmelab.com:8000, this will be very slow and in my home, some operation will hang forever.  after change the baseApiUrl, it works.

**Pull request closed without merging**
